
"""게임에서 여러 모듈이 공유하는 변경 가능한 기본 설정."""

# 네트워크
SERVER_IP = "127.0.0.1"
SERVER_PORT = 5555
NETWORK_BUFFER_SIZE = 4096
SERVER_SEED = 12345
MAX_PLAYERS = 12
NORMAL_MATCH_MIN_PLAYERS = 2
LOBBY_START_DELAY_MS = 3000
GAME_MODE_NORMAL = "normal"
GAME_MODE_DEBUG = "debug"

# 화면과 게임 루프
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 64

# 플레이어
PLAYER_MAX_HP = 100
PLAYER_NORMAL_SPEED = 5
PLAYER_SPRINT_SPEED = 8
PLAYER_HASTE_SPEED = 10
PLAYER_DASH_SPEED = 15
PLAYER_DASH_DURATION_MS = 200
PLAYER_DASH_COOLDOWN_MS = 1500
DEFAULT_WEAPON_ID = "pistol"
DEFAULT_BULLET_SIZE = 1
DEFAULT_BULLET_DAMAGE = 10
BULLET_IMAGE_FILE = "sprite_0017.png"
PISTOL_IMAGE_SIZE = (96, 48)

# 맵과 스폰
MAP_WIDTH_TILES = 200
MAP_HEIGHT_TILES = 200
SPAWN_MIN_X = 40
SPAWN_MAX_X = 160
SPAWN_MIN_Y = 40
SPAWN_MAX_Y = 160
MAP_HOUSE_COUNT = 48
MAP_HOUSE_MARGIN = 32
MAP_HOUSE_MIN_SIZE = 12
MAP_HOUSE_MAX_SIZE = 20
MAP_SAFE_ZONE_MIN = 72
MAP_SAFE_ZONE_MAX = 112
MAP_TREASURE_CHANCE = 1.0
MAP_HOUSE_PADDING = 4
MAP_BUSH_COUNT = 1100
MAP_BUSH_CLUSTER_COUNT = 42
MAP_BUSH_CLUSTER_RADIUS_MIN = 5
MAP_BUSH_CLUSTER_RADIUS_MAX = 10
MAP_BUSH_VISIBLE_DISTANCE = 224
BUSH_VISION_FOV_BONUS = 20
MAP_RUNE_COUNT = 24
MAP_WATER_RADIUS = 9
WATER_SPEED_MULTIPLIER = 0.72

# 카메라
CAMERA_FOV = 1.0
CAMERA_FOV_MAX = 1.35
SPRINT_CAMERA_FOV = 1.22
CAMERA_FOV_SMOOTH = 0.12

# 전투와 스킬
MELEE_RANGE = 150
BULLET_TARGET_DISTANCE = 1000
BOMB_DELAY_MS = 600
BOMB_RADIUS = 120
BOMB_DAMAGE = 30
BOMB_INSTALL_EFFECT_MS = 600
STUN_DURATION_MS = 2500
MAGNETIC_ZONE_FINAL_RATIO = 0.12
HASTE_DURATION_MS = 5000
VISION_DURATION_MS = 3000
SHIELD_DURATION_MS = 5000
STEALTH_DURATION_MS = 1500
STEALTH_COOLDOWN_MS = 10000
TELEPORT_DURATION_MS = 5000
TELEPORT_COOLDOWN_MS = 15000
SUPPLY_DROP_INTERVAL_MS = 8000
SUPPLY_DROP_CHANCE = 0.8
SUPPLY_DROP_MAX = 5
SUPPLY_HEAL_AMOUNT = 25
SUPPLY_BUFF_DURATION_MS = 5000
SUPPLY_DROP_RADIUS = 18
SUPPLY_DROP_LIFETIME_MS = 30000
SUPPLY_DROP_WARNING_MS = 2200
TRAINING_DUMMY_MAX_HP = 500
TRAINING_DUMMY_RESPAWN_MS = 900
DAMAGE_TEXT_LIFETIME_MS = 1500
EASTER_EGG_DISTANCE = 110
SUPPLY_REWARD_TYPES = ("heal", "haste", "shield", "skill")
CHEST_REWARD_TYPES = ("magazine", "skill")
INVENTORY_SIZE = (720, 210)
INVENTORY_X = (SCREEN_WIDTH - INVENTORY_SIZE[0]) // 2
INVENTORY_Y = 390
INVENTORY_ITEM_COLUMNS = 6
INVENTORY_ITEM_ALPHA = 75
EXPLOSION_DURATION_MS = 350
SKILL_COOLDOWN_MS = 5000
SCREEN_SHAKE_MAX = 12
MELEE_SHAKE = 3
MELEE_ATTACK_DURATION_MS = 350
MELEE_WEAPON_SCALE = 0.15
WEAPON_FIRE_ANIMATION_MS = 120
WEAPON_SMOKE_ANIMATION_MS = 260
SHIELD_ALPHA = 150
HEALTH_GREEN_THRESHOLD = 0.8
HEALTH_YELLOW_THRESHOLD = 0.4
HEAD_HITBOX_WIDTH_RATIO = 0.55
HEAD_HITBOX_HEIGHT_RATIO = 0.35
BODY_HITBOX_INSET_RATIO = 0.08
HEADSHOT_DAMAGE_MULTIPLIER = 2

# UI
HP_FRAME_SIZE = (360, 120)
VISION_OVERLAY_ALPHA = 170
MAIN_SCREEN_IMAGE_SIZES = {
	"MainProfile": (650, 182),
	"TitleText": (760, 381),
	"GameStart": (360, 116),
	"Practice": (360, 116),
	"Setting": (360, 126),
	"Exit": (360, 126),
}
AMMO_PANEL_SIZE = (360, 90)
AMMO_PANEL_MARGIN = (30, 30)
MAIN_WEAPON_PREVIEW_SIZE = (240, 120)

# 스킬 아이콘과 퀵슬롯 위치 조정값
SKILL_ICON_SIZE = 70
QUICK_SLOT_SIZE = 80
SKILL_PANEL_SIZE = (720, 180)
SKILL_PANEL_X = (SCREEN_WIDTH - SKILL_PANEL_SIZE[0]) // 2
SKILL_PANEL_Y = SCREEN_HEIGHT - SKILL_PANEL_SIZE[1] - 30

# 퀵슬롯을 옮기려면 QUICK_SLOT_START_X, QUICK_SLOT_Y를 조정합니다.
QUICK_SLOT_START_X = (SCREEN_WIDTH - QUICK_SLOT_SIZE * 3 - 40) // 2
QUICK_SLOT_Y = SCREEN_HEIGHT - QUICK_SLOT_SIZE - 80

# 스킬 인벤토리 안 아이콘의 시작 위치와 간격을 조정합니다.
SKILL_ICON_START_X = INVENTORY_X + 28
SKILL_ICON_START_Y = INVENTORY_Y + 62
SKILL_ICON_GAP_X = 18
SKILL_ICON_GAP_Y = 20

# 기존 코드와의 호환 별칭
ServerIp = SERVER_IP
ServerPort = SERVER_PORT
ScreenX = SCREEN_WIDTH
ScreenY = SCREEN_HEIGHT
PlayerSpd = PLAYER_NORMAL_SPEED
Bullet_Size = 30



